(function(f){var h=window.AmazonUIPageJS||window.P,k=h._namespace||h.attributeErrors,q=k?k("CustomerReviewsCommonAssets",""):h;q.guardFatal?q.guardFatal(f)(q,window):q.execute(function(){f(q,window)})})(function(f,h,k){function q(){}f.when("A","cr-log-utils","cr-uri-utils","cr-streaming-utils").register("cr-ajax-model",function(b,d,a,c){function e(c){var b=a.getUrlParametersMap()||{};b["overrides-marketplace-id"]&&(c=a.addKeyValuePair(c,"overrides-marketplace-id",b["overrides-marketplace-id"]));return c}
function l(a){g[a]&&(g[a].abort(),delete g[a])}function x(a,p,r,t,f,k,u,q){p=p||{};p.params=p.params||{};var y;y=k?k:m=m++;k=y;f=f?f:p.error||function(){};t=t?t:0;r=r?r:2;q=q?q:"FATAL";var A="FATAL"===q?0:1,w=p.finallyCallback||function(){};a=e(a);u||(u="reviewsAjax"+n++,h.uet&&h.uet("tc",u));p.params.scope=u;p.contentType="application/x-www-form-urlencoded;charset\x3dUTF-8";var z=p.success||function(){};p.success=function(a){delete g[k];"function"===typeof z&&z(a);"function"===typeof w&&w(a)};p.error=
function(c,b,e){l(k);c=c||{};var n=(c.http||{}).status||"[]";t++;t<r?(b="AJAX Post to "+a+" from "+h.location.href+" failed, status code passed through parameter was: "+b+", status code extracted from XHR HTTP object was: "+n+", attempt "+t+" of "+r+", error message was: \n "+e,d.logError(b,"WARN"),x(a,p,r,t,f,k,u,q)):(b="AJAX Post to "+a+" from "+h.location.href+" failed, status code passed through parameter was: "+b+", status code extracted from XHR HTTP object was: "+n+", exhausted "+r+" attempt(s), error message was: \n "+
e,d.logError(b,q),d.logCount("AjaxFailureFatal",A),"function"===typeof f&&f(c),"function"===typeof w&&w(c))};"function"!==typeof p.chunk&&(p.chunk=function(a){"appendFadeIn"===a[0]?c.appendFadeIn(a):"replace"===a[0]&&c.replace(a)});g[k]=b.post(a,p);return k}var n=0,m=1,g={};return{abort:l,post:x,postWithoutFatals:function(a,c,b,e,l,d,n){return x(a,c,b,e,l,d,n,"WARN")}}});"use strict";f.when("A","cr-jQuery","cr-log-utils","cr-number-utils").register("cr-A",function(b,d,a,c){b.getListFromState=function(a){var c=
b.map(d("#cr-state-object, .cr-state-object"),function(a){return d(a).data("state")});return b.reduce(c,function(c,b){b!==k&&b[a]!==k&&c.push(b[a]);return c},[])};b.getValueFromState=function(c){var e=b.getListFromState(c);1<e.length&&a.logError("More than one  value defined for key: "+c,"ERROR");return e[0]};var e={top:-100,left:-100};b.inView=function(a){a=a||d();if("function"===typeof a.offset){var c=(a.offset()||e).top-d(h).scrollTop();a=0<=c;c=c<d(h).height();return a&&c}return!1};b.onScreenAndVisible=
function(a,b){a=a||d();b=c.isFiniteNumber(b)?b:0;if(a instanceof d||a.jquery){if(!a.is(":visible"))return!1;a=a[0].getBoundingClientRect();return a.top>=0-b&&a.left>=0-b&&a.bottom<=d(h).height()+b&&a.right<=d(h).width()+b}return!1};b.compositeEventWrapper=function(c,e,d){var m=c;d&&(m=b.throttle(m,d,{trailing:!1}));return a.jsGuard(function(a){a&&(m(a),e&&a.$event&&a.$event.preventDefault())})};b.freeze=function(a){return"undefined"!==typeof Object&&"function"===typeof Object.freeze?Object.freeze(a):
a};b.isFrozen=function(a){return"undefined"!==typeof Object&&"function"===typeof Object.isFrozen?Object.isFrozen(a):!1};return b});"use strict";f.when("jQuery").register("cr-jQuery",function(b){return b});"use strict";f.declare("reviews-constants",{PUSH_STATE:!0,REPLACE_STATE:!1,RATING_SERVICE_CONTEXT_ID:"ReviewsConsumption",data:{REFTAG:"data-reftag",CSM_COUNTER:"data-csm-counter",getReviews:{STANDARD:"data-reviews-state-param",CHECKED:"data-reviews-param-checked",UNCHECKED:"data-reviews-param-unchecked"}},
events:{CONTENT_CHANGED:"reviews:content-changed",RELOAD:"reviews:content-reload",RELOAD_COMPLETE:"reviews:content-reload-complete",AUTOSCROLL_COMPLETE:"reviews:autoscroll-complete",FILTER_FIRE_AGGREGATE:"reviews:filter-action:aggregate:trigger",FILTER_FIRE_UPDATE:"reviews:filter-action:trigger",FILTER_AGGREGATE:"reviews:filter-action:aggregate",FILTER_PUSH:"reviews:filter-action:push-state",FILTER_REPLACE:"reviews:filter-action:replace-state",PAGINATION:"reviews:page-action",SEARCH_TEXTBOX:"reviews:search-textbox",
SEARCH_BUTTON:"reviews:search-button",VOTE:"reviews:vote-action",TOGGLE_CLASS_CLICK:"reviews:toggle-class:click",AJAX_POST:"reviews:ajax-post",SCROLL_TO_ELEMENT_CLICK:"reviews:scroll-to-element:click",FILTER_APPLY:"reviews:filter-action:apply",FILTER_CHANGE:"reviews:filter-action:change",FILTER_TAB_CLICKED:"reviews:filter-action:tab-clicked",FILTER_APPLY_BEGIN:"reviews:filter-action:apply-begin",FILTER_APPLY_SUCCESS:"reviews:filter-action:apply-success",FILTER_APPLY_ERROR:"reviews:filter-action:apply-error",
FILTER_APPLY_DONE:"reviews:filter-action:apply-done",INPUT_COMMENT:"reviews:input-comment",SUBMIT_COMMENT:"reviews:submit-comment",OPEN_SUBMISSION_COMMENT:"reviews:open-comment-submission",SORT_COMMENTS:"reviews:sort-comments",MORE_COMMENTS:"reviews:more-comments",EDIT_COMMENT:"reviews:edit-comment",CANCEL_EDIT_COMMENT:"reviews:cancel-edit-comment",DELETE_COMMENT:"reviews:delete-comment",SUBMIT_EDIT_COMMENT:"reviews:submit-edit-comment",MODIFY_EDIT_COMMENT:"reviews:modify-edit-comment",INPUT_PRODUCT_LINK:"reviews:input-product-link",
SELECT_PRODUCT_LINK:"reviews:select-product-link",STAR_RATING_CLICK:"ryp:star-rating-click",STAR_RATING_CLEAR:"ryp:star-rating-clear-click"},filterOptions:{SORT_KEY:"sortBy",HELPFUL:"helpful",RECENT:"recent",LEGACY_HELPFUL:"byRankDescending",LEGACY_RECENT:"bySubmissionDateDescending",MOBILE_HELPFUL:"sh",MOBILE_RECENT:"sd",STAR_KEY:"filterByStar",ALL_STARS:"all_stars",ONE_STAR:"one_star",TWO_STAR:"two_star",THREE_STAR:"three_star",FOUR_STAR:"four_star",FIVE_STAR:"five_star",POSTIVE:"positive",CRITICAL:"critical",
FORMAT_KEY:"formatType",ALL_FORMATS:"all_formats",CURRENT_FORMAT:"current_format",AVP_KEY:"reviewerType",ALL_REVIEWS:"all_reviews",AVP_ONLY:"avp_only_reviews",MEDIA_KEY:"mediaType",ALL_CONTENTS:"all_contents",MEDIA_ONLY:"media_reviews_only",LANGUAGE_KEY:"filterByLanguage",HEIGHT_KEY:"filterByHeight",WEIGHT_KEY:"filterByWeight"},keycodes:{ENTER:13,BACK_SPACE:8,SPACE:32},aui:{HIDDEN:"aok-hidden",NOWRAP:"aok-nowrap"}});"use strict";f.when("A","cr-string-utils","cr-log-utils").register("cr-popup",function(b,
d,a){function c(c){var l={};c&&c.data&&(l=c.data);var f=d.defaultIfBlank(l.url,c.$target.find("a").andSelf().filter("a").attr("href")),n=d.defaultIfBlank(l.title,"CustomerReviews"),n=""+n,m="";b.each({width:"500",height:"500",resizable:"1",scrollbars:"1",toolbar:"0",status:"1"},function(a,c){a=d.defaultIfBlank(l[c],a);m+=c+"\x3d"+a+","});var m=m.slice(0,-1),g=null;try{(g=h.open(f,n,m))?g.focus():a.logError("Unable to move focus to popup window with data: "+d.stringify(l),"ERROR"),c.$event.preventDefault()}catch(v){a.logError("Unable to open window with parameters: "+
d.stringify(l),"FATAL",v)}return g}b.declarative("cr-popup",["click"],a.jsGuard(c));return{popup:c}});"use strict";f.when("A","cr-jQuery","reviews-constants","cr-ajax-model","cr-string-utils","cr-global-view").register("cr-generic-declarative-actions",function(b,d,a,c,e,l){function f(a){g(a)&&a.data.selector&&a.data.cssClass&&(d(a.data.selector).toggleClass(a.data.cssClass),a.$event.preventDefault(),b.trigger("a:pageUpdate"))}function n(a){g(a)&&a.data.scrollToSelector&&(l.scrollTo(a.data.scrollToSelector,
0),a.$event.preventDefault())}function m(a){if(g(a)&&a.data.url&&a.data.params){a.$event.preventDefault();b.declarative.remove(a.$currentTarget,p.AJAX_POST);a=a.data;var e=a.params,n=d(a.indicatorSelector)[0],l=v(d.fn.hide,a.hideOnSuccessSelector),f=v(d.fn.show,a.showOnFailureSelector);d(a.removeOnLoadSelector).remove();c.post(a.url,{params:e,indicator:n,success:l,error:f})}}function g(a){return a&&a.data&&a.$event&&"function"===typeof a.$event.preventDefault}function v(a,c){if(c&&"function"===typeof a)return function(){var b=
d(c);0<b.length&&a.call(b)}}var p=a.events;b.declarative(p.TOGGLE_CLASS_CLICK,"click",f);b.declarative(p.SCROLL_TO_ELEMENT_CLICK,"click",n);b.declarative(p.AJAX_POST,"click",m);return{toggleCssClass:f,scrollToElement:n,ajaxPost:m}});"use strict";f.register("cr-global-model",function(){return{generateUrl:function(b,d){b&&"/"!==b.charAt(b.length-1)&&(b+="/");b&&d&&(b=b+"ref\x3d"+d);return b}}});"use strict";f.when("A","a-expander","cr-jQuery","reviews-constants","cr-string-utils").register("cr-global-view",
function(b,d,a,c,e){function l(a){var c="";if(a&&a.closest!==k){var b=a.closest("*["+g.REFTAG+"]");b&&(c=b.attr(g.REFTAG))}e.isBlank(c)&&a&&a.closest!==k&&(a=a.closest("*[rel]"))&&(c=a.attr("rel"));return e.defaultIfBlank(c,"cm_cr_unknown")}function f(a){return a&&"function"===typeof a.is?a.is("*["+g.getReviews.CHECKED+"]")&&a.is("*["+g.getReviews.UNCHECKED+"]"):!1}function n(a){return a&&a.has!==k&&a.is!==k?0<a.find(":checked").length||a.is(":checked"):!1}function m(a,c){return a&&a.attr!==k&&c?
e.parseJSON(a.attr(c))||{}:{}}var g=c.data;b.on("a:pageUpdate",function(){d!==k&&d.initializeExpanders()});return{getReviewsStateParamsFromElement:function(a){var c=b.reduce(g.getReviews,function(a,c){return a+"*["+c+"],"},"").slice(0,-1),e;c&&a&&a.closest!==k&&(e=a.closest(c));return f(e)?n(e)?m(e,g.getReviews.CHECKED):m(e,g.getReviews.UNCHECKED):m(e,g.getReviews.STANDARD)},getReftag:function(c){var b;c&&c.$target&&(b=c.$target);c&&c.id&&(b=a("#"+c.id));c&&c.expander&&c.expander.$expander&&(b=c.expander.$expander);
b=l(b);"cm_cr_unknown"===b&&c&&c.data&&c.data.reftag&&(b=c.data.reftag);return b},getReftagByDom:l,scrollTo:function(c,b){c=a(c).offset();b=b||0;var e=a("#cr-state-object").data("state"),e=e!==k&&e.disableScroll;c&&c.top!==k&&!e&&(a("html,body").stop(),a("html,body").animate({scrollTop:c.top-b},{queue:!1,duration:500}))}}});"use strict";f.when("cr-A","cr-jQuery","cr-lazy-widget-model","cr-lazy-widget-view","cr-log-utils","cr-number-utils","cr-string-utils","cr-uri-utils","ready").register("cr-lazy-widget-controller",
function(b,d,a,c,e,l,f,n){function m(d){var g=b.getValueFromState("lazyWidgetDomainWhitelist"),l=n.getCurrentHostname();if(g)b:{for(var m=0;m<g.length;m++)if(f.endsWith(l,g[m])){e.logCount("LazyWidgetInvalidDomain",0);break b}e.logError("AJAX triggered from invalid domain: "+l,"WARN");e.logCount("LazyWidgetInvalidDomain",1)}else e.logCount("LazyWidgetInvalidDomain",1),e.logError("AJAX triggered with null whitelist from domain: "+l,"WARN");a.loadLazyWidgets(c.getLazyWidgetStubs())&&(e.logCount("LazyWidgetTrigger",
1),e.logCount("LazyWidgetTrigger:"+d,1))}var g={};g.bufferPixels=l.convertToInteger(b.getValueFromState("lazyWidgetLoaderBufferPixels"),1E3);g.delayBeforeTriggering=l.convertToInteger(b.getValueFromState("lazyWidgetLoaderDelayBeforeTriggering"),5E3);g.triggerLazyLoadIfWidgetWithinBuffer=function(e){a.lazyLoadHasTriggered()||c.getLazyWidgetStubs().each(function(a,c){if(b.onScreen(d(c),g.bufferPixels))return m("scroll"),b.off("scroll",g.triggerLazyLoadIfWidgetWithinBuffer),!1})};var h={};g.logVisibleStubMetrics=
function(a){c.getLazyWidgetStubs().each(function(a,c){a=d(c);c=a.data("widget-name");!h[c]&&b.onScreen(a)&&(e.logCount("VisibleLazyWidgetStub",1),e.logCount("VisibleLazyWidgetStub:"+c,1),h[c]=!0)})};b.on("scroll",g.logVisibleStubMetrics);b.on("scroll",g.triggerLazyLoadIfWidgetWithinBuffer);d(c.getHoverTargets()).mouseenter(function(){m("hover")});e.logCount("LazyWidgetTrigger",0);return b.freeze(g)});"use strict";f.when("cr-A","cr-ajax-model","ready").register("cr-lazy-widget-model",function(b,d){var a=
{},c=b.getValueFromState("lazyWidgetLoaderUrl"),e=!1;a.loadLazyWidgets=function(a){if(!e&&0<a.length){e=!0;var f=b.getValueFromState("asin"),n=b.getValueFromState("lazyWidgetCsrfToken");a=b.reduce(a,function(a,c){return a+"\x26lazyWidget\x3d"+b.$(c).data("widget-name")},c+"?asin\x3d"+f+"\x26csrf\x3d"+n);d.postWithoutFatals(a,{success:q,cache:!1,headers:{"cache-control":"no-cache"}});return!0}return!1};a.lazyLoadHasTriggered=function(){return e};return b.freeze(a)});"use strict";f.when("cr-A","cr-jQuery",
"ready").register("cr-lazy-widget-view",function(b,d){var a={},c=b.getValueFromState("lazyWidgetLoaderHoverTargetsSelector")||"";a.getLazyWidgetStubs=function(){return d(".cr-lazy-widget")};a.getHoverTargets=function(){d(c)};return b.freeze(a)});"use strict";f.when("A").register("cr-log-utils",function(b){function d(a,b,d){h.ueLogError&&("string"!==typeof b&&(b="FATAL"),d?h.ueLogError(d,{message:a,logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}):h.ueLogError({message:a},{logLevel:b.toUpperCase(),
attribution:"CustomerReviewsJS"}))}function a(a,b){return"string"===typeof b?b+a:"CustomerReviews:"+a}return{logError:d,jsGuard:function(a){if("function"===typeof a)return function(){try{return a.apply(this,arguments)}catch(b){d("Uncaught Error in function","FATAL",b)}};d("Unable to wrap non-function","ERROR");return a},incrementCount:function(c,b){h.ue&&(c=a(c,b),b=h.ue.count(c)||0,h.ue.count(c,b+1))},logCount:function(c,b,d){h.ue&&(c=a(c,d),h.ue.count(c,b))}}});"use strict";f.register("cr-mash-utils",
function(){var b=!1;f.when("mash").execute(function(){b=!0});return{isMash:function(){return b}}});"use strict";f.when("A","cr-log-utils").register("cr-number-utils",function(b,d){return{convertToInteger:function(a,c){if(a===parseInt(a,10))return a;if(null!==a&&a!==k&&""!==a)return parseInt(a.replace(/[^0-9]/g,""),10);if(c!==k)return c;d.logError("convertToInteger","Cannot convert "+a+" to Integer");return 0},isFiniteNumber:function(a){return"number"===typeof a&&!isNaN(a)&&isFinite(a)}}});"use strict";
f.when("A","cr-jQuery").register("cr-streaming-utils",function(b,d){return{appendFadeIn:function(a){if(null!==a&&2<a.length&&null!==a[1]&&null!==a[2]){var c=a[1];a=d(a[2]).hide();d(c).append(a);b.fadeIn(a,500,"ease-in-out",function(){})}},replace:function(a){if(null!==a&&2<a.length&&null!==a[1]&&null!==a[2]){var c=a[2];d(a[1]).replaceWith(d(c))}}}});"use strict";f.when("A","cr-log-utils").register("cr-string-utils",function(b,d){function a(a){return null===a||a===k?!0:0===b.trim(a).length}return{defaultIfBlank:function(c,
b){return a(c)?b:c},isBlank:a,parseJSON:function(a){try{return b.parseJSON(a)}catch(e){d.logError("Unable to parse JSON object","ERROR",e)}return null},startsWith:function(a,b){return a===b?!0:null===a||null===b?!1:0===a.indexOf(b)},endsWith:function(a,b){if(a===b)return!0;if(null===a||null===b)return!1;var d=a.lastIndexOf(b);return-1!==d&&d===a.length-b.length},stringify:function(a){return h.JSON&&h.JSON.stringify?h.JSON.stringify(a):a}}});"use strict";f.when("A").register("cr-uri-utils",function(b){function d(a){a=
a||h.location.href;var c={},d=a.indexOf("?"),f=a.indexOf("#");a=a.slice(d+1,f>d?f:k)||"";d=[];-1<a.indexOf("\x26")?d=a.split("\x26"):-1<a.indexOf("\x3d")&&(d=[a]);b.each(d,function(a,b){0<a.indexOf("\x3d")&&(a=a.split("\x3d"),c[a[0]]=a[1])});return c}return{getUrlParametersMap:d,addKeyValuePair:function(a,b,e){e=e||0;if(d(a)[b]===e||!a||!b)return a;b="?"+b+"\x3d"+e;return-1<a.indexOf("?")?a.replace("?",b+"\x26"):a+b},getCurrentHostname:function(){return h.location.hostname}}});"use strict";f.when("A",
"cr-uri-utils","cr-string-utils","3p-urijs","cr-jQuery").register("cr-extended-uri-utils",function(b,d,a,c,e){function f(){return c(h.location.href)}function k(){return f().query()}return e.extend(d,{getCurrentUri:f,getCurrentQueryString:k,getCurrentQueryParameters:function(){return c.parseQuery(k())},isAmazonDomain:function(b){if("string"===typeof b||b instanceof String)b=c(b);var d=a.startsWith(b.domain(),"amazon");!1===d&&(b=b.hostname(),b=b.substring(b.indexOf(".")+1),d=a.startsWith(b,"amazon"));
return d},setQueryParameters:function(d,e){if("string"===typeof d||d instanceof String)d=c(d);b.each(e,function(b,c){a.isBlank(b)?d.removeSearch(c):d=d.setSearch(c,b)});return d},setReftag:function(b,d){if("string"===typeof b||b instanceof String)b=c(b);for(var e=b.segment(),f=!1,h=e.length-1;0<=h;h--)if(a.startsWith(e[h],"ref\x3d")){f=!0;e[h]="ref\x3d"+d;break}f||e.push("ref\x3d"+d);b.segment(e);return b}})});"use strict";f.when("A","cr-jQuery").register("histogram-trigger",function(b,d){function a(){b.onScreen(d("#histogramTable"))&&
b.trigger("scroll")}b.on.afterLoad(a);return{triggerHistogram:a}})});
/* ******** */
(function(b){var e=window.AmazonUIPageJS||window.P,f=e._namespace||e.attributeErrors,a=f?f("CustomerReviewsMedleyAssets",""):e;a.guardFatal?a.guardFatal(b)(a,window):a.execute(function(){b(a,window)})})(function(b,e,f){b.when("A","medley-twister-view","medley-twister-model","ready").register("medley-twister-controller",function(a,c,g){function b(a){a=g.getASIN();var d=c.getDisplayedASIN();d&&a!==d&&(c.fadeReviews(!0),g.getReviews(d,function(){g.setASIN(d)},function(){},function(){c.fadeReviews(!1)}))}
var e=c.getLoadedASIN();g.setASIN(e);a.on("a:pageUpdate",b);return{onTwist:b}});"use strict";b.when("A","cr-jQuery").register("medley-twister-view",function(a,c){return{getDisplayedASIN:function(){return String(c("#ASIN").val()||"")},getLoadedASIN:function(){return(c("#cr-state-object").data("state")||{}).asin||""},fadeReviews:function(a){!1===a?c("#cm-cr-review-list .review,#most-recent-reviews-content .review").css("opacity",1):c("#cm-cr-review-list .review,#most-recent-reviews-content .review").css("opacity",
.5)}}});"use strict";b.when("A","cr-global-model","cr-ajax-model","cr-uri-utils","cr-jQuery").register("medley-twister-model",function(a,c,b,e,f){function h(a){var b=e.getUrlParametersMap()||{};b.asin=a;return b}var d;return{setASIN:function(a){d=a||""},getASIN:function(){return d},getReviews:function(a,c,e,d){var k=f("#cr-state-object").data("state");"string"===typeof a&&10===a.length?b.post(k.medleyReviewsAjaxUrl,{params:h(a),attribution:"getMedleyReviews",success:c,error:e,finallyCallback:d}):
"function"===typeof d&&d()}}})});
/* ******** */
(function(l){var p=window.AmazonUIPageJS||window.P,r=p._namespace||p.attributeErrors,b=r?r("CustomerReviewsVotingAssets"):p;b.guardFatal?b.guardFatal(l)(b,window):b.execute(function(){l(b,window)})})(function(l,p,r){l.when("A","vote-model","vote-view","a-modal").register("vote-controller",function(b,a,c,e){function g(a,b){k(a,b);c.showElementByCssSelector(a,b.inFlight)}function k(a,b){c.hideElementByCssSelector(a,b.hideVoteComponents);b.hideAbuseComponents&&c.hideElementByCssSelector(a,b.hideAbuseComponents)}
function f(d,f){f.isReportAbuse&&(d=b.$("#mobile-abuse-"+f.voteInstanceId),e.get(d).hide());g(d,f.cssSelectors);a.submitVote(f.ajaxUrl,f.voteValue,f.voteInstanceId,f.csrfT,f.voteDimension,function(a){if(!0===a){a=d;var b=f.cssSelectors;k(a,b);c.showElementByCssSelector(a,b.onSuccess)}else a=d,b=f.cssSelectors,k(a,b),c.showElementByCssSelector(a,b.onError)},function(){var a=d,b=f.cssSelectors;k(a,b);c.showElementByCssSelector(a,b.onError)})}b.declarative("reviews:vote-action","click",function(a){f(a.$target,
a.data);a.$event.preventDefault()});return{submitVote:f}});l.when("A","cr-ajax-model").register("vote-model",function(b,a){return{submitVote:function(b,e,g,k,f,d,l){a.post(b,{params:{voteInstanceId:g,voteValue:e,csrfT:k,voteDimension:f},attribution:"submitVote",success:d,error:l})}}});l.when("A").register("vote-view",function(b){function a(a,b){return a.closest(".cr-vote").find(b)}return{hideThankYouAlert:function(b){a(b,".cr-vote-success").addClass("aok-hidden")},showThankYouAlert:function(b){a(b,
".cr-vote-success").removeClass("aok-hidden")},showErrorAlert:function(b){a(b,".cr-vote-error").removeClass("aok-hidden")},showFeedback:function(b){a(b,".cr-vote-feedback").removeClass("aok-hidden")},hideFeedback:function(b){a(b,".cr-vote-feedback").addClass("aok-hidden")},hideButtons:function(b){a(b,".cr-vote-buttons").addClass("aok-hidden")},hideElementByCssSelector:function(b,e){a(b,e).addClass("aok-hidden")},showElementByCssSelector:function(b,e){a(b,e).removeClass("aok-hidden")}}})});
/* ******** */
(function(l){var p=window.AmazonUIPageJS||window.P,r=p._namespace||p.attributeErrors,b=r?r("CustomerReviewsGalleryAssets"):p;b.guardFatal?b.guardFatal(l)(b,window):b.execute(function(){l(b,window)})})(function(l,p,r){l.when("A","load").register("review-image-asset-loader",function(b){var a=!1;b.ajax("/gp/customer-reviews/aj/private/reviewsGallery/get-image-gallery-assets",{method:"post",success:function(b){l.load.css(b.reviewsLightboxCSS);var e=document.createElement("script");e.type="text/javascript";
e.async=!0;e.setAttribute("crossorigin","anonymous");e.src=b.reviewsLightboxJS;document.getElementsByTagName("head")[0].appendChild(e);a=!0;l.register("review-image-assets-loaded",{})},error:function(){var a;a="/gp/customer-reviews/aj/metrics/log-values?noCache="+(new Date).getTime();a+="&SimpleStack:ReviewImageAssetLoaderFailure=1";p.Image&&((new Image).src=a)}});return{isLoaded:function(){return a}}});l.when("A","cr-jQuery","cr-log-utils","reviews-constants","review-image-assets-loaded").register("review-image-binder",
function(b,a,c,e){function g(b,d,e,f,g){if(!(b&&d&&e instanceof a&&f instanceof a&&g instanceof a))return c.logError("Invalid parameters for imageBinder.initializeEventHandlers with ASIN: "+b+", galleryName: "+d+", $popoverTrigger: "+e+", $thumbnails: "+f+", $galleryLink: "+g,"FATAL"),!1;var p="reviewsLightbox-ready-"+d;f.click(function(){k(b,d);var c=f.index(this);e.click();l.when(p).execute(function(){a("#"+d).trigger("jumpToImageAtIndex",c)})});g.click(function(){k(b,d);e.click();l.when(p).execute(function(){a("#"+
d).trigger("hideImmersiveView")})});return!0}function k(a,b){if(!a||!b)return c.logError("Invalid parameters for imageBinder.initializeImageGallery with ASIN: "+a+", galleryName: "+b,"FATAL"),!1;if(f)return!0;(new ReviewsLightbox(b,"DESKTOP")).initializeForAsin(a);return f=!0}var f=!1,d={};l.when("reviewsLightbox-js").execute(function(){var b=a("#reviews-image-gallery-container"),c=b.attr("data-asin");0<b.length&&c&&g(c,"reviews-image-gallery",b.find(".a-popover-trigger"),b.find(".review-image-tile"),
b.find(".reviews-image-gallery-link"))});b.on(e.events.RELOAD_COMPLETE,function(){d={}});return{bindReview:function(b,c,e){var f=new ReviewGallery(e,"DESKTOP"),g=a("#"+c);g.find(".review-image-tile").each(function(c){a(this).click(function(){d[b]||(f.initializeForReview(b),d[b]=!0);g.find(".a-popover-trigger").click();l.when("reviewsLightbox-ready-"+e).execute(function(){f.render();f.showImageAtIndex(c)})})})},initializeImageGallery:k,initializeEventHandlers:g}});l.when("A","cr-jQuery",
"cr-video-model","cr-video-view","reviews-constants").register("cr-video-controller",function(b,a,c,e,g){function k(){b.each(a(".review-views .review"),function(a){a&&a.id&&(a=c.getEmbedInfo(a.id))&&(c.isAiryLoaded()||c.loadAssets(),e.embedVideo(a))})}b.on(g.events.RELOAD_COMPLETE,function(){k()});k();return{initAll:k}});l.when("cr-jQuery").register("cr-video-model",function(b){var a=!1;return{getEmbedInfo:function(a){var e="video-block-"+a,g=b("#"+a+" .video-url").val(),k=b("#"+a+" .video-slate-img-url").val(),
f=b("#cr-video-swf-url").val();return a&&g&&f?{videoDomId:e,videoUrl:g,videoSlateImgUrl:k,videoSwfUrl:f}:!1},isAiryLoaded:function(){return a},loadAssets:function(){var c=b("#cr-airy-js-source-url").val(),e=b("#cr-airy-css-source-url").val();"string"===typeof c&&"string"===typeof e&&(l.load.js(c),l.load.css(e));a=!0}}});l.when("cr-jQuery","afterLoad").register("cr-video-view",function(b){return{embedVideo:function(a){l.when("Airy").execute(function(b){b.embed({parentId:a.videoDomId,streamingUrls:[a.videoUrl],
slateImages:{preloadSlate:a.videoSlateImgUrl},swfUrl:a.videoSwfUrl,desiredMode:"html"})})}}})});
/* ******** */
(function(h){var n=window.AmazonUIPageJS||window.P,q=n._namespace||n.attributeErrors,e=q?q("CustomerReviewsFilteringAssets",""):n;e.guardFatal?e.guardFatal(h)(e,window):e.execute(function(){h(e,window)})})(function(h,n,q){h.when("cr-A","cr-jQuery","cr-filtering-view","cr-filtering-model","cr-global-view","reviews-constants","cr-streaming-utils").register("cr-filtering-controller",function(e,f,b,d,r,g,k){function m(l){var a=!1,c=!1;l.toggleFilters&&(c=!0);d.setASIN(b.getLoadedFilterParam("asin"));
a=d.setReviewerType(l.reviewerType,c)||a;a=d.setFormatType(l.formatType,c)||a;a=d.setFilterByKeyword(l.filterByKeyword,c)||a;a=d.setFilterByLanguage(l.filterByLanguage,c)||a;a=d.setSortOrder(l.sortOrder,c)||a;a=d.setStarFilter(l.filterByStar,c)||a;a=d.setPageNumber(l.pageNumber,c)||a;a=d.setHeightFilter(l.filterByHeight,c)||a;return a=d.setWeightFilter(l.filterByWeight,c)||a}function h(a){if(m(a.data)||a.data.forceReload)a.data.sortOrder&&b.setSortDropdown(a.data.sortOrder),b.hideReviewLoadError(),
b.hideReviews(),b.showLoadingSpinner(),e.trigger(g.events.FILTER_APPLY_BEGIN,a),d.getReviews(function(){b.showReviews();e.trigger(g.events.FILTER_APPLY_SUCCESS,a)},function(){b.showReviewLoadError();e.trigger(g.events.FILTER_APPLY_ERROR,a)},function(){b.hideLoadingSpinner();e.trigger(g.events.FILTER_APPLY_DONE,a);e.trigger(g.events.RELOAD_COMPLETE)},function(a){"appendFadeIn"===a[0]?k.appendFadeIn(a):"replace"===a[0]&&k.replace(a)},r.getReftag(a)),a.data.scrollToSelector&&r.scrollTo(a.data.scrollToSelector,
0)}function p(a){a&&a.data&&h(a)}function a(a){a&&a.data&&a.$target&&a.data.filterType&&(a.data[a.data.filterType]=a.$target.val(),h(a))}function c(a){a&&a.data&&a.data.filterType&&(b.deactivateFilterTabHeaders(),b.activateFilterTabHeader(a.data.filterType),b.changeFilterOptionsTo(a.data.filterType))}d.setReviewsAjaxUrl(b.getReviewsAjaxUrl());e.declarative(g.events.FILTER_APPLY,"click",e.compositeEventWrapper(p,!0,100));e.declarative(g.events.FILTER_CHANGE,"change",e.compositeEventWrapper(a,!0,100));
e.declarative(g.events.FILTER_TAB_CLICKED,"click",c);d.setReviewerType(b.getLoadedFilterParam("reviewerType"),!1);d.setFormatType(b.getLoadedFilterParam("formatType"),!1);d.setFilterByKeyword(b.getLoadedFilterParam("filterByKeyword"),!1);d.setFilterByLanguage(b.getLoadedFilterParam("filterByLanguage"),!1);d.setStarFilter(b.getLoadedFilterParam("filterByStar"),!1);d.setSortOrder(b.getLoadedFilterParam("sortOrder"),!1);d.setPageNumber(b.getLoadedFilterParam("pageNumber"),!1);return{setFilterParams:m,
onFilterApply:p,onFilterChange:a,onFilterTabClicked:c}});"use strict";h.when("A","cr-ajax-model","ready").register("cr-filtering-model",function(e,f){function b(){return m.asin||""}function d(){return n||""}function h(a,c){c?m[a]=c:delete m[a]}function g(a,c,d){var b=!1;a&&c!==q&&(b=k(a)!==c,!b&&d&&(c="CLEAR_VALUE",b=!0),h(a,c));return b}function k(a){return m[a]||""}var m={},n="",p;return{getReviews:function(a,c,d,b,g){var e=n;p&&f.abort(p);g&&(e+="ref\x3d"+g);p=f.post(e,{params:m,attribution:"getFilteredReviews",
success:a,error:c,finallyCallback:function(){d();p=0},chunk:b})},setASIN:function(a){var c=b()!==a;h("asin",a);return c},getASIN:b,setReviewsAjaxUrl:function(a){var c=d()!==a;n=a||"";return c},getReviewsAjaxUrl:d,setReviewerType:function(a,c){return g("reviewerType",a,c)},getReviewerType:function(){return k("reviewerType")},setFormatType:function(a,c){return g("formatType",a,c)},getFormatType:function(){return k("formatType")},setFilterByKeyword:function(a,c){return g("filterByKeyword",a,c)},getFilterByKeyword:function(){return k("filterByKeyword")},
setFilterByLanguage:function(a,c){return g("filterByLanguage",a,c)},getFilterByLanguage:function(){return k("filterByLanguage")},setSortOrder:function(a,c){return g("sortBy",a,c)},getSortOrder:function(){return k("sortBy")},setStarFilter:function(a,c){return g("filterByStar",a,c)},getStarFilter:function(){return k("filterByStar")},setPageNumber:function(a,c){return g("pageNumber",a,c)},getPageNumber:function(){return k("pageNumber")},setHeightFilter:function(a,c){return g("filterByHeight",a,c)},getHeightFilter:function(){return k("filterByHeight")},
setWeightFilter:function(a,c){return g("filterByWeight",a,c)},getWeightFilter:function(){return k("filterByWeight")},getFilterParams:function(){return m||{}},updateFilterParam:h}});"use strict";h.when("cr-A","cr-jQuery","a-dropdown","ready").register("cr-filtering-view",function(e,f,b){return{getReviewsAjaxUrl:function(){return(f("#cr-state-object").data("state")||{}).reviewsAjaxUrl||""},showLoadingSpinner:function(){var d=e.getValueFromState("onLoadShowHideElements");f(d).removeClass("aok-hidden")},
hideLoadingSpinner:function(){var d=e.getValueFromState("onLoadShowHideElements");f(d).addClass("aok-hidden")},hideReviews:function(){f(".filterable-reviews-content").addClass("aok-hidden")},showReviews:function(){f(".filterable-reviews-content").removeClass("aok-hidden")},showReviewLoadError:function(){f(".review-load-error").removeClass("aok-hidden")},hideReviewLoadError:function(){f(".review-load-error").addClass("aok-hidden")},deactivateFilterTabHeaders:function(){f(".cr-tab-header-text").removeClass("cr-tab-active")},
activateFilterTabHeader:function(d){f(".cr-tab-header-text-"+d).addClass("cr-tab-active")},changeFilterOptionsTo:function(d){f(".cr-tab-content").addClass("aok-hidden");f(".cr-tab-content-"+d).removeClass("aok-hidden")},getLoadedFilterParam:function(d){return(f("#cr-state-object").data("state")||{})[d]||""},setSortDropdown:function(d){b.getSelect("cm-cr-sort-dropdown").setValue(d)}}});"use strict";h.when("cr-A","cr-lighthut-terms-view","reviews-constants","cr-log-utils").register("cr-lighthut-terms-controller",
function(e,f,b,d){function h(b){b&&b.filterByKeyword!==q&&(f.setSelected(b.filterByKeyword),d.incrementCount("LighthutTermClicked"))}e.on(b.events.FILTER_APPLY_BEGIN,e.compositeEventWrapper(function(b){b&&b.data&&h(b.data)}));return{onFilterApplied:h}});"use strict";h.when("A","cr-jQuery","ready").register("cr-lighthut-terms-view",function(e,f){return{setSelected:function(b){b=b.replace(/ /g,"_");var d=(b=f("#cr-lighthouse-term-"+b))&&b.hasClass("cr-lighthut-term-selected");f(".cr-lighthut-term-selected").removeClass("cr-lighthut-term-selected");
d||b.addClass("cr-lighthut-term-selected")}}})});
/* ******** */
