(function(k){var n=window.AmazonUIPageJS||window.P,q=n._namespace||n.attributeErrors,e=q?q("AmazonDevicesDetailPageUtilityAssets",""):n;e.guardFatal?e.guardFatal(k)(e,window):e.execute(function(){k(e,window)})})(function(k,n,q){k.when("A").execute(function(e){e.declarative("popup-window","click",function(c){var a=c.data.windowName||"popupWindow",b=c.data.windowOptions||"width\x3d600,height\x3d400,scrollbars\x3dyes";c.$event.preventDefault();n.open(c.$target.prop("href"),a,b)})});"use strict";k.when("A").register("ods-element-factory",
function(e){var c=e.$;return{getHiddenInput:function(a,b){return c("\x3cinput\x3e").prop("name",a).prop("type","hidden").prop("value",b)}}});"use strict";k.register("ods-url-utils",function(){return{getUrlParam:function(e){for(var c=null,a=n.location.search.substr(1).split("\x26"),b=0;b<a.length;b++){var d=a[b].split("\x3d");d[0]===e&&(c=d[1])}return c}}});"use strict";k.when("A").register("csmCounter",function(e){var c=e.$;return{register:function(a,b,d){a&&b&&d&&c(a).bind(b,c.proxy(this.increment,
this,d))},increment:function(a){a&&n.ue.count(a,(n.ue.count(a)||0)+1)},update:function(a,b){a&&"number"===typeof b&&n.ue.count(a,b)}}});"use strict";k.register("function-utils",function(){return{throttle:function(e,c,a){var b,d,f,g=null,h=0;a||(a={});var m=function(){h=!1===a.leading?0:(new Date).getTime();g=null;f=e.apply(b,d);g||(b=d=null)};return function(){var l=(new Date).getTime();h||!1!==a.leading||(h=l);var p=c-(l-h);b=this;d=arguments;0>=p||p>c?(g&&(clearTimeout(g),g=null),h=l,f=e.apply(b,
d),g||(b=d=null)):g||!1===a.trailing||(g=setTimeout(m,p));return f}},debounce:function(e,c,a){var b;return function(){var d=this,f=arguments;clearTimeout(b);b=setTimeout(function(){b=null;a||e.apply(d,f)},c);a&&!b&&e.apply(d,f)}},memoize:function(e,c){var a={};return function(){for(var b=0<arguments.length?"":"%NO_ARGUMENTS%",d=0;d<arguments.length;d++)b&&(b+="-"),b+="object"===typeof arguments[d]?JSON.stringify(arguments[d]):arguments[d];a.hasOwnProperty(b)||(a[b]=c.apply(e,arguments));return a[b]}}}});
"use strict";k.when("A").register("odsRefTagUtils",function(e){var c=e.$;return{send:function(a,b){if(!a)throw Error("refTag is not defined");c.post((b||"/gp/digital/fiona/ajax/log.html")+"/ref\x3d"+a)}}});"use strict";k.when("A").register("ods-image-utilities",function(e){function c(b,a){var f=new Image;f.onload=function(){a.resolve(b)};f.onerror=function(){a.reject(b)};f.src=b}var a=e.$;return{preloadImage:function(b,d){var f=a.Deferred(),g;c(b,f);d&&e.capabilities.hires&&(g=a.Deferred(),c(d,g));
return{image:f.promise(),hiResImage:g?g.promise():q}},preloadImages:function(b){for(var d=[],f=0;f<b.length;f++){var g=a.Deferred();c(b[f],g);d.push(g.promise())}return d}}});"use strict";k.when("A").register("ODSEventDispatcher",function(e){return e.createClass({init:function(){this._callbacks={}},registerCallback:function(c,a){var b=this._callbacks[c]||[];-1===b.indexOf(a)&&b.push(a);this._callbacks[c]=b},unregisterCallback:function(c,a){if(c=this._callbacks[c])a=c.indexOf(a),-1<a&&c.splice(a,1)},
dispatch:function(c){var a=this._callbacks[c];if(a)for(var b=0;b<a.length;b++)a[b].apply(this,Array.prototype.slice.call(arguments,1))}})});"use strict";k.when("A","jQuery").register("BuyboxManagerFactory",function(e,c){function a(b,a,g,h){var m=e.copy(g);c.each(m,function(e){-1===["initialize","reset"].indexOf(e)&&(b[e]=h?c.proxy(a,null,e):c.proxy(g,e))})}function b(b,f,g,h){var e=function(r){if(!p&&(h?(h.initialize(),a(l,e,h,!1)):k=new g,p=new f(k),c.each(b,function(b,a){l[a]=c.proxy(p,a)}),"string"===
typeof r))return l[r].apply(p,Array.prototype.slice.call(arguments,1))},l={reset:function(){p?(h&&h.reset(),k&&k.reset(),p.reset()):e()},initialize:e},p,k;h&&a(l,e,h,!0);c.each(b,function(b,a){l[a]=c.proxy(e,null,a)});return l}return{create:function(a,f,g){return b(a,f,g)},extend:function(a,f,g){return b(a,f,null,g)}}});"use strict";k.when("jQuery","BuyboxManagerViewHelper").register("BuyboxManagerFormHelper",function(e,c){function a(b,a){return'\x3cinput type\x3d"hidden" name\x3d"'+b+'" value\x3d"'+
a+'" /\x3e'}function b(b){return 0<=b.attr("id").search("buyNow")}function d(b){return 0<=b.attr("id").search("addToCart")||0<=b.attr("id").search("mobile-installments")}function f(b,a){return e.map(b,function(b){return e(b).attr(a)})}'input[name\x3d"%NAME%"]'.replace("%NAME%","verificationSessionID");var g='input[name\x3d"%NAME%"]'.replace("%NAME%","a"),h='input[name\x3d"%NAME%"]'.replace("%NAME%","oid"),m='input[name\x3d"%NAME%"]'.replace("%NAME%","quantity"),l='input[name\x3d"%NAME%"]'.replace("%NAME%",
"asin"),k='input[name\x3d"%NAME%"]'.replace("%NAME%","offeringID"),u='input[name\x3d"%NAME%"]'.replace("%NAME%","quantity"),r=[g,h,m].concat([l,k,u]).join(", ");return{removeAllFormFields:function(b){b.find(r).remove()},getHiddenInputHTML:a,isFormBuyNow:b,isFormAddToCart:d,createMobileAppFormInputs:function(b){var f=b[0],g,h,d;f&&(g=f.asin,h=f.offerId,d=f.quantity);for(f=1;f<b.length;f++)g+="|"+b[f].asin,h+="|"+b[f].offerId,d+="|"+b[f].quantity;return""+(a("asin",g)+a("offeringID",h)+a("quantity",
d))},getViewData:function(a){if(b(a)){var e=f(a.find(l),"value")[0].split("|"),t=f(a.find(k),"value")[0].split("|");a=f(a.find(u),"value")[0].split("|");return c.buildRawData(e,t,a)}if(d(a))return e=f(a.find(g),"value"),t=f(a.find(h),"value"),a=f(a.find(m),"value"),c.buildRawData(e,t,a);throw Error("Add to order button not handled in buyBoxManagerFormHelper");},updateMobileAppFormInputsWithSubscriptionData:function(b,f,g){if(!e.isEmptyObject(b._digitalSubscriptionAsinMap)){var h=[],d=b._digitalSubscriptionAsinMap,
c;for(c in d)if(d.hasOwnProperty(c)){var m=d[c],l=m.name,m=m.value;h.push('input[name\x3d"%NAME%"]'.replace("%NAME%",l));h.push('input[name\x3d"%NAME%"]'.replace("%NAME%",m));delete d[c]}l=h.join(",");g.find(l).remove();b._digitalSubscriptionAsinMap=d}g="";for(d=1;d<f.length;d++)f[d].customAttribute&&(l="custom-name.%INDEX.1".replace("%INDEX",d),m="custom-value.%INDEX.1".replace("%INDEX",d),h=f[d],g+=a(l,h.customAttribute.name)+a(m,h.customAttribute.value),b._digitalSubscriptionAsinMap||(b._digitalSubscriptionAsinMap=
{}),b._digitalSubscriptionAsinMap[h.asin]={index:d,name:l,value:m});return g}}});"use strict";k.when("A","jQuery","BuyboxManagerViewBase").register("BuyboxManagerView",function(e,c,a){return a.extend({init:function(){this._super()},moveFieldsToContainer:function(b,a){for(var f=1,g=[],h;h===q||0<h.length;)h=b.find(this.getHiddenSelector("ASIN."+f)),0<h.length&&g.push(h.get(0),b.find(this.getHiddenSelector("offerListingID."+f)).get(0),b.find(this.getHiddenSelector("quantity."+f)).get(0)),f++;a.append(g)},
render:function(b){this._super(b);var a=this;this.$forms.each(function(f){var g=c(this),h=g.find('input[type\x3d"hidden"][name^\x3d"ASIN."]'),e=c.isArray(b)?b.length:0,l=a.$fieldsContainers.get(f);h.each(function(){var b=c(this);if(!b.parent().is(l)){var f=a._getAsinIndex(b);e++;b.prop("name","ASIN."+e);g.find('input[type\x3d"hidden"][name\x3d"offerListingID.'+f+'"]').prop("name","offerListingID."+e);g.find('input[type\x3d"hidden"][name\x3d"quantity.'+f+'"]').prop("name","quantity."+e)}})})},buildHTML:function(b,
a){return this.getHiddenInputHTML("ASIN."+a,b.asin)+this.getHiddenInputHTML("offerListingID."+a,b.offerId)+this.getHiddenInputHTML("quantity."+a,b.quantity)},getDataFromDOM:function(){var b=[],a=this.$fieldsContainers.first(),f=this;a.find('input[type\x3d"hidden"][name^\x3d"ASIN."]').each(function(){var g=c(this),h=f._getAsinIndex(g);b.push({asin:g.val(),offerId:a.find(f.getHiddenSelector("offerListingID."+h)).val(),quantity:parseInt(a.find(f.getHiddenSelector("quantity."+h)).val(),10)})});return b},
_getAsinIndex:function(b){return parseInt(b.prop("name").substring(5),10)}})});"use strict";k.when("A","jQuery").register("BuyboxManagerViewBase",function(e,c){return e.createClass({init:function(){this.reset()},registerAtcBtn:function(a){this.$atcBtns=this.$atcBtns.add(a)},registerForm:function(a){a="string"===typeof a?c(a):a;if(a instanceof c&&0<a.length&&0===this.$forms.has(a).length){this.$forms=this.$forms.add(a);var b=this.createFieldsContainer(a);this.moveFieldsToContainer(a,b)}},createFieldsContainer:function(a){var b=
a.find(".buyboxManagerHiddenFieldsContainer");0===b.length&&(b=c('\x3cdiv class\x3d"buyboxManagerHiddenFieldsContainer"\x3e'),a.append(b));0===this.$fieldsContainers.has(b).length&&(this.$fieldsContainers=this.$fieldsContainers.add(b));return b.first()},moveFieldsToContainer:function(a,b){throw Error("The view must override the moveFieldsToContainer function");},getHiddenSelector:function(a,b){var d='input[type\x3d"hidden"]';"string"===typeof a&&(d+='[name\x3d"'+a+'"]');"string"===typeof b&&(d+='[value\x3d"'+
b+'"]');return d},getHiddenInputHTML:function(a,b){return'\x3cinput type\x3d"hidden" name\x3d"'+a+'" value\x3d"'+b+'" /\x3e'},render:function(a){this.appendFormData(a)},appendFormData:function(a,b){b=b||1;var d="";if(c.isArray(a))for(var f=0;f<a.length;f++)d+=this.buildHTML(a[f],b+f);this.$fieldsContainers.html(d)},reset:function(){this.$forms=c();this.$fieldsContainers=c();this.registerForm(c("#addToCart"));this.$atcBtns=c();this.registerAtcBtn(c("#add-to-cart-button"));this.registerAtcBtn(c("#bb_to_cfg_button"));
this.registerAtcBtn(c("#buy-now-button"))}})});"use strict";k.when("jQuery").register("BuyboxManagerViewHelper",function(e){var c={FORM:"form",AW_MASH:"aw_mash",SHOW_HCTP_ATTACH:"show-hctp-attach",UNKNOWN:q};return{ViewType:c,getAtcBtnViewType:function(a){var b=c.UNKNOWN;a instanceof e||(a=e(a));var d=a.closest('.a-declarative[data-action\x3d"aw-mash"]'),f=a.closest('.a-declarative[data-action\x3d"show-hctp-attach"]');return 0<d.length?c.AW_MASH:0<a.closest("form").length?c.FORM:0<f.length?c.SHOW_HCTP_ATTACH:
b},buildRawData:function(a,b,d){var f={},g=[];e.each(a,function(a,c){var e=b.length>a?b[a]:"";a=d.length>a?parseInt(d[a],10):1;var k=c+":"+e;f.hasOwnProperty(k)?g[f[k]].quantity+=a:f[k]=g.push({asin:c,offerId:e,quantity:a})-1});return g}}});"use strict";k.when("A","jQuery","ODSEventDispatcher","ods-url-utils","BuyboxManagerViewBase").register("BuyboxManagerController",function(e,c,a,b,d){return e.createClass({init:function(b){if(!(b instanceof d))throw new TypeError("The view must inherits from BuyboxManagerViewBase");
this._view=b;this._eventDispatcher=new a;this._enableEvents(!0);this.reset();var g=this;e.on("a:dropdown:mobileQuantityDropDown:select",function(b){g.setPageAsinQuantity(parseInt(b.value,10))});this._isFreeFormQuantityPickerPresent()&&this._makeAwareOfFreeFormQuantity()},_enableEvents:function(b){c.each("UpsellAsinAdded UpsellAsinRemoved UpsellAsinChanged PageAsinAdded PageAsinReplaced PageAsinChanged".split(" "),c.proxy(function(a,d){b?(this["register"+d]=c.proxy(this._eventDispatcher,"registerCallback",
d),this["unregister"+d]=c.proxy(this._eventDispatcher,"unregisterCallback",d)):(delete this["register"+d],delete this["unregister"+d])},this))},_parseInitialAsins:function(){var b=this._view.getDataFromDOM();if(b)for(var a=0;a<b.length;a++)this[0===a?"setPageAsin":"setUpsellAsin"](b[a].asin,b[a].offerId,b[a].quantity)},_dispatchSetUpsellAsinEvents:function(b,a,d,c){c!==d&&(0===c&&0<d?this._eventDispatcher.dispatch("UpsellAsinAdded",b,a,d,c):0===d&&0<c&&this._eventDispatcher.dispatch("UpsellAsinRemoved",
b,a,d,c),this._eventDispatcher.dispatch("UpsellAsinChanged",b,a,d,c))},_indexOfAsin:function(b,a){a=a||"";for(var d=0;d<this._asinsData.length;d++)if(this._asinsData[d].asin===b&&this._asinsData[d].offerId===a)return d;return-1},_isFreeFormQuantityPickerPresent:function(){return 0<c('select[id$\x3d"-predefinedQuantitiesDropdown"]').length},_makeAwareOfFreeFormQuantity:function(){var a=this;e.on("buyBoxQuantityChanged",function(b,d){a.setPageAsinQuantity(d)});var d=parseInt(b.getUrlParam("qty"),10);
d&&a.setPageAsinQuantity(d)},setUpsellAsin:function(b,a,d,c){if("string"!==typeof b||0>=b.length)throw new TypeError("The asin argument is required");var e=this._indexOfAsin(b,a),k=0;a=a||"";d="number"===typeof d?Math.max(0,d):1;if(0===e)throw Error("To modify the pageAsin, use setPageAsin() instead.");if(0<e)c=this._asinsData[e],k=c.quantity,0>=d?this._asinsData.splice(e,1):c.quantity=d;else if(0<d)this._asinsData.push({asin:b,offerId:a,quantity:d,customAttribute:c});else return!1;this.render();
this._dispatchSetUpsellAsinEvents(b,a,d,k,e);return!0},registerForm:function(b){this._view.registerForm(b);this.render()},registerAtcBtn:function(b){this._view.registerAtcBtn(b);this.render()},setPageAsin:function(b,a,d){if("string"!==typeof b||0>=b.length)throw new TypeError("The asin argument is required");var c=this._indexOfAsin(b,a),e=0<this._asinsData.length?this._asinsData[0].quantity:0;a=a||"";if(0>=d)throw new TypeError("The quantity of the page asin must be \x3e 0.");d="number"===typeof d?
Math.max(1,d):1;if(0===c&&d===e)return!1;0<c&&this.setUpsellAsin(b,a,0);this._asinsData[0]={asin:b,offerId:a,quantity:d};this.render();-1<c?this._eventDispatcher.dispatch("PageAsinReplaced",b,a,d,e):this._eventDispatcher.dispatch("PageAsinAdded",b,a,d);this._eventDispatcher.dispatch("PageAsinChanged",b,a,d);return!0},setPageAsinQuantity:function(b){var a=this._asinsData&&this._asinsData.length&&this._asinsData[0];a&&this.setPageAsin(a.asin,a.offerId,b)},addUpsellAsin:function(b,a,d){d=d||1;for(var c=
0;c<this._asinsData.length;c++){var e=this._asinsData[c];if(e.asin===b){this.setUpsellAsin(b,a,e.quantity+d);return}}this.setUpsellAsin(b,a,d)},render:function(){this._view.render(this._asinsData)},getAsins:function(){return e.copy(this._asinsData)},getUpsellAsins:function(){var b=this.getAsins();b.splice(0,1);return b},getPageAsin:function(){return e.copy(this._asinsData[0])},reset:function(){this._asinsData=[];this._parseInitialAsins()}})});"use strict";k.when("BuyboxManagerController","BuyboxManagerView",
"BuyboxManagerFactory","jQuery").register("BuyboxManager",function(e,c,a,b){return a.create("getAsins getUpsellAsins setUpsellAsin getPageAsin setPageAsin registerUpsellAsinChanged registerUpsellAsinAdded registerUpsellAsinRemoved registerPageAsinChanged registerPageAsinAdded registerPageAsinReplaced unregisterUpsellAsinChanged unregisterUpsellAsinRemoved unregisterUpsellAsinAdded unregisterPageAsinChanged unregisterPageAsinAdded unregisterPageAsinReplaced addUpsellAsin registerForm registerAtcBtn".split(" "),
e,c)});"use strict";k.when("jQuery","BuyboxManagerViewHelper").register("BuyboxManagerMashHelper",function(e,c){return{createInputs:function(a){var b={a:[],oid:[],quantity:[]};e.each(a,function(a,c){b.a.push(c.asin);b.oid.push(c.offerId);b.quantity.push(c.quantity)});b.a=b.a.join("|");b.oid=b.oid.join("|");b.quantity=b.quantity.join("|");return b},getViewData:function(a){var b=a.inputs.a.split("|"),d=a.inputs.oid.split("|");a=a.inputs.quantity.split("|");return c.buildRawData(b,d,a)},setDeclarativeMultiple:function(a){a.buttonID=
"add-multiple-to-cart"},getDeclarativeDataFromBtn:function(a){return a.closest('.a-declarative[data-action\x3d"aw-mash"]').data("awMash")},isAddToCart:function(a){return"add-to-cart"===a.buttonID},updateInputWithSubscriptionData:function(a,b,d){if(!e.isEmptyObject(a._digitalSubscriptionAsinMap)){var c=a._digitalSubscriptionAsinMap,g;for(g in c)if(c.hasOwnProperty(g)){var h=c[g],k=h.index;if(d.length<=k||d[k].asin!==g)b[h.name]&&delete b[h.name],b[h.value]&&delete b[h.value],delete c[g]}a._digitalSubscriptionAsinMap=
c}e.each(d,function(d,c){if(c.customAttribute){var e="custom-name."+(d+1)+".1",f="custom-value."+(d+1)+".1";b[e]=c.customAttribute.name;b[f]=c.customAttribute.value;a._digitalSubscriptionAsinMap||(a._digitalSubscriptionAsinMap={});a._digitalSubscriptionAsinMap[c.asin]={index:d,name:e,value:f}}})}}});"use strict";k.when("ODSBuyboxManagerController","BuyboxManager","BuyboxManagerFactory","A","jQuery").register("ODSBuyboxManager",function(e,c,a,b,d){return a.extend(["addMetadata","getMetadata","getAsins",
"getPageAsin","getUpsellAsins"],e,c)});"use strict";k.when("BuyboxManager","ODSBuyboxAsinMetadata","A","jQuery").register("ODSBuyboxManagerController",function(e,c,a,b){return a.createClass({init:function(){this.reset()},addMetadata:function(b){if(!(b instanceof c))throw Error("The argument metadata must be an instance of ODSBuyboxAsinMetadata");if(!b.isValid())throw Error("The metadata is NOT valid");this._metadatas[b.asin+":"+b.offerId]=b.clone()},getMetadata:function(b,a){return this._metadatas[b+
":"+a]},getMetadatas:function(){return a.copy(this._metadatas)},enhanceAsinsData:function(a){if("undefined"!==typeof a&&null!==a&&0!==a.length){var c=this;b.isArray(a)?a=b.map(a,function(a){return b.extend({},a,{metadata:c.getMetadata(a.asin,a.offerId)})}):a.metadata=c.getMetadata(a.asin,a.offerId)}return a},getPageAsin:function(){return this.enhanceAsinsData(e.getPageAsin())},getUpsellAsins:function(){return this.enhanceAsinsData(e.getUpsellAsins())},getAsins:function(){return this.enhanceAsinsData(e.getAsins())},
reset:function(){this._metadatas={}}})});"use strict";k.when("A","jQuery").register("ODSBuyboxAsinMetadata",function(e,c){var a=e.createClass({init:function(b,a,c,e,h,k,l){this.asin=b;this.offerId=a;this.buyingPrice=c;this.listingPrice=e;this.title=h;this.imageUrl=k;this.availabilityMessage=l},isValid:function(){var b="string"===typeof this.asin&&0<this.asin.length;return"number"===typeof this.buyingPrice&&b},clone:function(){return new a(this.asin,this.offerId,this.buyingPrice,this.listingPrice,
this.title)}});return a});"use strict";k.when("A","jQuery","a-modal").register("singleton-popup-modal",function(e,c,a){function b(b){null===h?(g=f.appendTo(c("body")),h=a.create(g,b)):h.update(b);h.show()}function d(){h&&h.hide()}var f=c('\x3cdiv style\x3d"display:none"\x3e'),g=null,h=null;e.declarative("cfg-singleton-modal-close","click",d);e.declarative("cfg-singleton-modal-open","click",function(a){b({inlineContent:a.data.inlineContent,header:a.data.header,width:a.data.width||"502",position:"triggerRight"},
!0)});return{show:b,hide:d,destroy:function(){h&&(a.remove(h),h=null)}}});"use strict";k.when("A").register("MakoCommonCartHelper",function(e){var c=e.$,a=e.createClass({init:function(b,a,c,e){this.sessionId=b||"";this.clientName=a||"";this.asinsData=c||[];this.additionalData=e||{};this.reftag;this.hasBeenPosted=!1},setSessionId:function(a){this.sessionId=a;return this},setClientName:function(a){this.clientName=a;return this},setAsinsData:function(a){if(Array.isArray(a))return this.asinsData=a,this},
addAsinData:function(a,c,e){this.asinsData.push({asin:a,offerId:c,quantity:e});return this},setAdditionalData:function(a){this.additionalData=a;return this},setReftag:function(a){this.reftag=a;return this},sendRequest:function(){if(this.hasBeenPosted)k.log("Request has already been sent.","WARN");else if(this._verifyRequest()){var a=this._buildRequestData();this.hasBeenPosted=!0;return c.ajax({url:"/gp/add-to-cart/json/"+(this.reftag?"ref\x3d"+this.reftag:""),type:"POST",data:a})}},_verifyRequest:function(){var a=
!0;this.sessionId&&""!==this.sessionId||(a=!1,k.log("SessionId is undefined or blank","WARN"));this.asinsData&&this.asinsData.length||(a=!1,k.log("No asins data exist for cart handler request","WARN"));return a},_buildRequestData:function(){var a={};a.verificationSessionID=this.sessionId;a.clientName=this.clientName;for(var c=0;c<this.asinsData.length;c++){var e=this.asinsData[c];a["asin."+c]=e.asin;a["offeringID."+c]=e.offerId||e.offerListingID;a["quantity."+c]=e.quantity}if(this.additionalData)for(var g in this.additionalData)this.additionalData.hasOwnProperty(g)&&
(a[g]=this.additionalData[g]);return a}});return{createRequest:function(b,c){return new a(b,c)}}});"use strict";k.when().register("ExtraDataHelper",function(){function e(a,b){return a&&a.name&&0===a.name.indexOf(b)}function c(a,b){var c=Array.prototype.slice.call(a.elements);a=c.filter(function(a){return a&&a.tagName&&"input"===a.tagName.toLowerCase()&&e(a,["custom-name",b,""].join("."))});c=c.filter(function(a){return a&&a.tagName&&"input"===a.tagName.toLowerCase()&&e(a,["custom-value",b,""].join("."))});
return{names:a,values:c}}function a(a,b){return a!==q&&null!==a?a:b}function b(b,c,d){c=a(c,"([0-9]+)");d=a(d,"([0-9]+)");return new RegExp([b,c,d].join("."))}function d(a,b){var c=document.createElement("input");c.type="hidden";c.name=a;c.value=b;return c}function f(a,c,d,e){var f=b("custom-name",a);return c.reduce(function(b,c){var g=f.exec(c);if(g){var g=g[1],h=["custom-value",a,g].join(".");b[g]={name:d(c),value:e(h)}}return b},{})}function g(a,b,c,d){Object.keys(b).forEach(function(e){var f=
b[e],g=["custom-name",a,e].join(".");e=["custom-value",a,e].join(".");"object"===typeof f&&(c(g,f.name),d(e,f.value))})}function h(a,b){var c=Object.keys(a),d=function(b){return a[b]};return f(b,c,d,d)}function k(a,b,c){var d=function(b,c){a[b]=c};g(c,b,d,d)}function l(a,b){a=c(a,b);var d=a.names.map(function(a){return a.name}),e=function(a){return function(b){var c=a.filter(function(a){return a.name===b});return c.length?c[0].value:q}};return f(b,d,e(a.names),e(a.values))}function p(a,b,e){var f=
c(a,e),h=function(b){return function(c,e){var f=b.filter(function(a){return a.name===c});f.length?f.forEach(function(a){a.value=e}):a.appendChild(d(c,e))}};g(e,b,h(f.names),h(f.values))}function n(a){return Object.keys(a).reduce(function(b,c){c=a[c];b[c.name]=c.value;return b},{})}function r(a,b){var c=Object.keys(a).reduce(function(b,c){c=a[c];b[c.name]=c;return b},{});Object.keys(b).forEach(function(d){if(c[d])c[d].value=b[d];else{var e=w(a),f={name:d,value:b[d]};a[e]=f;c[d]=f}});return a}function v(a,
b){return a-b}function w(a){a=Object.keys(a).map(function(a){return parseInt(a)}).sort(v);if(a.length){if(1!==a[0])return 1;for(var b=1;b<a.length;b++)if(1!==a[b]-a[b-1])return a[b-1]+1;return a.length+1}return 1}return{getObjectExtraData:function(b,c){c=a(c,1);return n(h(b,c))},setObjectExtraData:function(b,c,d){d=a(d,1);c=r(h(b,d),c);k(b,c,d)},getFormExtraData:function(b,c){if(!b)return{};c=a(c,1);return n(l(b,c))},setFormExtraData:function(b,c,d){b&&(d=a(d,1),c=r(l(b,d),c),p(b,c,d))}}})});
/* ******** */
(function(e){var h=window.AmazonUIPageJS||window.P,k=h._namespace||h.attributeErrors,c=k?k("DetailPagePreRegistrationAssets",""):h;c.guardFatal?c.guardFatal(e)(c,window):c.execute(function(){e(c,window)})})(function(e,h,k){e.when("A","jQuery","a-checkbox","a-dropdown","ExtraDataHelper").register("PreRegistration.View",function(c,d,b,g,f){return c.createClass({init:function(){this.reset()},reset:function(){this._giftingCheckbox=b("#gift-wrap");this._giftingCheckboxElement=d("#gift-wrap");this._accountLinkingCheckbox=
b("#account-linking");this._installmentAccountLinkingCheckbox=b("#installment-account-linking");this._desktopQuantityDropdown=g.getSelect("#quantity");this._mobileQuantityDropdown=g.getSelect("#mobileQuantityDropDown");this._quantityAlert=d("#preregistrationQuantityAlert");this._installmentQuantityAlert=d("#installmentPreregistrationQuantityAlert");this._giftingAlert=d("#preregistrationGiftingAlert");this._installmentGiftingAlert=d("#installmentPreregistrationGiftingAlert");this._declaratives=d("#atc-declarative, #buyNow .a-declarative");
this._forms=d("form#addToCart, form#mobile-installments, form#buyNow, form#buyNowCheckout, form#oneClickBuy, form#buyNowOneClickCheckout");this._quantityAlert.length&&(this._quantityAlertFormatString=this._quantityAlert.html())},updateQuantityLimit:function(b){this._quantityAlert.length&&this._quantityAlertFormatString&&(b=this._quantityAlertFormatString.replace("$PREREG_MAX_QUANTITY",b),this._quantityAlert.html(b),this._installmentQuantityAlert.html(b))},_setDeclarativeExtraData:function(b){this._declaratives.each(function(){var a=
d(this),c=a.data("action");c&&(a=a.data(c))&&a.inputs&&f.setObjectExtraData(a.inputs,b)})},_setFormExtraData:function(b){this._forms.each(function(){f.setFormExtraData(this,b)})},setAccountLinkingAttributeValue:function(b){var a={};a.isDevicePreRegistered=b;this._setDeclarativeExtraData(a);this._setFormExtraData(a)},_isCheckboxChecked:function(b){return!b.isEmpty()&&b.isChecked()},isGiftingChecked:function(){return this._isCheckboxChecked(this._giftingCheckbox)},isAccountLinkingChecked:function(){return this._isCheckboxChecked(this._accountLinkingCheckbox)},
isInstallmentAccountLinkingChecked:function(){return this._isCheckboxChecked(this._installmentAccountLinkingCheckbox)},getQuantity:function(){return this._desktopQuantityDropdown?this._desktopQuantityDropdown.val():this._mobileQuantityDropdown?this._mobileQuantityDropdown.val():1},scrollGiftingIntoView:function(){this._giftingCheckboxElement.length&&!c.onScreen(this._giftingCheckboxElement,5)&&this._giftingCheckboxElement[0].scrollIntoView()},_hide:function(b){b.addClass("aok-hidden")},_show:function(b){b.removeClass("aok-hidden")},
_isHidden:function(b){return b.hasClass("aok-hidden")},showGiftingAlert:function(){this._show(this._giftingAlert);this._show(this._installmentGiftingAlert)},hideGiftingAlert:function(){this._hide(this._giftingAlert);this._hide(this._installmentGiftingAlert)},showQuantityAlert:function(){this._show(this._quantityAlert);this._show(this._installmentQuantityAlert)},hideQuantityAlert:function(){this._hide(this._quantityAlert);this._hide(this._installmentQuantityAlert)},isGiftingAlertHidden:function(){return this._isHidden(this._giftingAlert)},
enableAccountLinkingCheckbox:function(b){this._accountLinkingCheckbox.enable();this._installmentAccountLinkingCheckbox.enable();d("#preRegCheckboxText").removeClass("a-color-tertiary");d("#installmentPreRegCheckboxText").removeClass("a-color-tertiary");b&&(this._accountLinkingCheckbox.check(),this._installmentAccountLinkingCheckbox.check())},disableAccountLinkingCheckbox:function(){this._accountLinkingCheckbox.uncheck();this._installmentAccountLinkingCheckbox.uncheck();this._accountLinkingCheckbox.disable();
this._installmentAccountLinkingCheckbox.disable();d("#preRegCheckboxText").addClass("a-color-tertiary");d("#installmentPreRegCheckboxText").addClass("a-color-tertiary")},isAccountLinkingCheckboxEnabled:function(){return this._accountLinkingCheckbox.isEnabled()},updateAccountLinkingCheckbox:function(b){b?(this._accountLinkingCheckbox.check(),this._installmentAccountLinkingCheckbox.check()):(this._accountLinkingCheckbox.uncheck(),this._installmentAccountLinkingCheckbox.uncheck())},openPopup:function(b){h.open(b,
"popupWindow","width\x3d600,height\x3d400,scrollbars\x3dyes")}})});e.when("A","PreRegistration.View","PreRegistration.Metrics").register("PreRegistration.Controller",function(c,d,b){var g=c.$,f,e=c.createClass({init:function(a){this._view=new d;this._metrics=new b;this.reset(a);this._bindEventsOnce()},reset:function(a){this._view.reset();this._bindEventsDOM();"object"===typeof a?(this._showStatus=a.showStatus,this._maxQuantityLimit=a.maxQuantity,this._defaultValue=a.defaultValue,this._status=a.status,
this._asin=a.asin,this._lastAccountLinkingValue=this._defaultValue,this._view.updateQuantityLimit(this._maxQuantityLimit),this._view.setAccountLinkingAttributeValue(this._defaultValue),this._showStatus&&this._view.isGiftingChecked()&&this._giftingCheckboxChecked(),this._checkQuantity(this._view.getQuantity()),this._showStatus?this._metrics.emitGiftingAndAccountLinkingLoadedMetric(this._asin):this._metrics.emitGiftingLoadedMetric(this._asin)):this._view.setAccountLinkingAttributeValue("false")},_checkQuantity:function(a){a>
this._maxQuantityLimit&&this._isStatusAllowedConditional()?(this._view.scrollGiftingIntoView(),this._disableAccountLinkingCheckbox(),this._metrics.emitALForceUncheckedQuantityHigh(this._asin),this._view.isGiftingAlertHidden()&&this._view.showQuantityAlert()):this._view.isGiftingChecked()||(this._enableAccountLinkingCheckbox(),this._view.hideQuantityAlert())},_giftingCheckboxChecked:function(){this._view.hideQuantityAlert();this._view.showGiftingAlert();this._view.isAccountLinkingChecked()&&this._metrics.emitALForceUncheckedGiftingSelected(this._asin);
this._disableAccountLinkingCheckbox()},_giftingCheckboxUnchecked:function(){this._view.hideGiftingAlert();this._enableAccountLinkingCheckbox();this._checkQuantity(this._view.getQuantity())},_enableAccountLinkingCheckbox:function(){if(!this._view.isAccountLinkingCheckboxEnabled()){var a=this._lastAccountLinkingValue;this._view.enableAccountLinkingCheckbox(a);this._view.setAccountLinkingAttributeValue(a?"true":"false")}},_disableAccountLinkingCheckbox:function(){this._view.isAccountLinkingCheckboxEnabled()&&
(this._lastAccountLinkingValue=this._view.isAccountLinkingChecked(),this._view.disableAccountLinkingCheckbox(),this._view.setAccountLinkingAttributeValue("false"))},_bindEventsOnce:function(){c.on("a:pageUpdate",this._handlePageUpdate.bind(this));c.on("a:dropdown:selected:quantity",this._handleQuantityChange.bind(this));c.on("a:popover:beforeSlide:preRegistration-secview",this._handlePopupClickMobile.bind(this));c.declarative("detail-page-gifting-declarative","click",this._handleGiftingClick.bind(this));
c.declarative("mako-gifting-declarative","click",this._handleGiftingClick.bind(this));c.declarative("mako-gifting-declarative-mobile","click",this._handleGiftingClick.bind(this));c.declarative("mako-preReg-declarative","click",this._handleAccountLinkingClick.bind(this));c.declarative("mako-installment-preReg-declarative","click",this._handleInstallmentAccountLinkingClick.bind(this));c.declarative("preReg-popup-window","click",this._handlePopupClick.bind(this));c.declarative("preReg-popup-window",
"mouseenter",this._handlePopupHover.bind(this));c.declarative("installment-preReg-popup-window","click",this._handlePopupClick.bind(this));c.declarative("installment-preReg-popup-window","mouseenter",this._handlePopupHover.bind(this))},_bindEventsDOM:function(){g("#installments-button").click(this._handleATC.bind(this,"ATC"));g("#add-to-cart-button").click(this._handleATC.bind(this,"ATC"));g("#buy-now-button").bind("click.makoPreRegistration",this._handleATC.bind(this,"BUYNOW"));g("#one-click-button").click(this._handleATC.bind(this,
"ONECLICK"))},_handlePageUpdate:function(){this._view.reset();var a=this._defaultValue;this._showStatus&&(a=this._view.isAccountLinkingChecked());this._view.setAccountLinkingAttributeValue(a?"true":"false")},_handleQuantityChange:function(a){this._checkQuantity(a.value)},_handleGiftingClick:function(a){this._isInputEvent(a)&&(this._view.isGiftingChecked()?(this._giftingCheckboxChecked(),this._metrics.emitGiftingCheckedMetric(this._asin)):(this._giftingCheckboxUnchecked(),this._metrics.emitGiftingUncheckedMetric(this._asin)))},
_handleAccountLinkingClick:function(a){this._isInputEvent(a)&&((a=this._view.isAccountLinkingChecked())?this._metrics.emitALCheckedMetric(this._asin):this._metrics.emitALUncheckedMetric(this._asin),this._lastAccountLinkingValue=a,this._view.updateAccountLinkingCheckbox(a),this._view.setAccountLinkingAttributeValue(a?"true":"false"))},_handleInstallmentAccountLinkingClick:function(a){this._isInputEvent(a)&&((a=this._view.isInstallmentAccountLinkingChecked())?this._metrics.emitALCheckedMetric(this._asin):
this._metrics.emitALUncheckedMetric(this._asin),this._lastAccountLinkingValue=a,this._view.updateAccountLinkingCheckbox(a),this._view.setAccountLinkingAttributeValue(a?"true":"false"))},_handlePopupClick:function(a){a.$event.preventDefault();a=a.$target.prop("href");this._view.openPopup(a);this._metrics.emitWhyIsThisImportantClickedMetric(this._asin)},_handlePopupClickMobile:function(a){this._metrics.emitWhyIsThisImportantClickedMetric(this._asin)},_handlePopupHover:function(a){this._metrics.emitPopupHoverMetric(this._asin)},
_handleATC:function(a){this._metrics.emitATCGiftingALSelectionMetric(this._asin,a,this._view.isGiftingChecked(),this._view.isAccountLinkingChecked())},_isInputEvent:function(a){return"input"===a.targetTag.toLowerCase()},_isStatusAllowedConditional:function(){return"ALLOWED_CONDITIONAL"===this._status}});return{getInstance:function(a){f?a&&f.reset(a):f=new e(a);return f}}});e.when("A","odsRefTagUtils").register("PreRegistration.Metrics",function(c,d){return c.createClass({emitGiftingAndAccountLinkingLoadedMetric:function(b){d.send("PREREGISTRATION_"+
b+"_GIFTING_AL_LOADED")},emitGiftingLoadedMetric:function(b){d.send("PREREGISTRATION_"+b+"_ONLY_GIFTING_LOADED")},emitALForceUncheckedQuantityHigh:function(b){d.send("PREREGISTRATION_"+b+"_AL_FORCE_UNCHECKED_QUANTITYHIGH")},emitALForceUncheckedGiftingSelected:function(b){d.send("PREREGISTRATION_"+b+"_AL_FORCE_UNCHECKED_GIFTINGSELECTED")},emitGiftingCheckedMetric:function(b){d.send("PREREGISTRATION_"+b+"_GIFTING_CHECKED")},emitGiftingUncheckedMetric:function(b){d.send("PREREGISTRATION_"+b+"_GIFTING_UNCHECKED")},
emitALCheckedMetric:function(b){d.send("PREREGISTRATION_"+b+"_AL_CHECKED")},emitALUncheckedMetric:function(b){d.send("PREREGISTRATION_"+b+"_AL_UNCHECKED")},emitWhyIsThisImportantClickedMetric:function(b){d.send("PREREGISTRATION_"+b+"_WHY_IS_THIS_IMPORTANT_CLICKED")},emitPopupHoverMetric:function(b){d.send("PREREGISTRATION_"+b+"_WHY_IS_THIS_IMPORTANT_HOVER")},emitATCGiftingALSelectionMetric:function(b,c,f,e){f?d.send("PREREGISTRATION_"+b+"_"+c+"_GIFTING_CHECKED"):d.send("PREREGISTRATION_"+b+"_"+c+
"_GIFTING_UNCHECKED");e?d.send("PREREGISTRATION_"+b+"_"+c+"_AL_CHECKED"):d.send("PREREGISTRATION_"+b+"_"+c+"_AL_UNCHECKED")}})})});
/* ******** */
